# -*- coding: utf-8 -*-
"""Credit card fraud detection using Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYojtKVBOBeCLvcQAM7eW_gSb3voN6j1

# **Data Cleaning**
"""

import pandas as pd
data = pd.read_csv("/content/creditcard.csv")
data.head(5)

pd.options.display.max_columns = None
data.head(5)

data.tail()

data.shape

print("Number of columns:{}".format(data.shape[1]))
print("Number of columns:{}".format(data.shape[0]))

data.info()

data.isnull().sum()

"""# **Scaling**"""

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data['Amount'] = sc.fit_transform(pd.DataFrame(data['Amount']))

data.head()

data = data.drop(['Time'],axis=1)
data.head()

"""# **Remove Duplicates**"""

data.duplicated().any()

data = data.drop_duplicates()
data.shape

data['Class'].value_counts()

"""# **Visualization**"""

import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('ggplot')

sns.countplot(data=data,x='Class')
plt.show()

x = data.drop('Class',axis = 1)
y = data['Class']

"""# **Model Train and Test**"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score
from sklearn.tree import DecisionTreeClassifier

classifier = {
    "Logistic Regression": LogisticRegression(),
    "Decision tree": DecisionTreeClassifier()
}

for name, clf in classifier.items():
  print(f"\n============{name}============")
  clf.fit(x_train,y_train)
  y_pred = clf.predict(x_test)
  print(f"\n Accuracy :{accuracy_score(y_test,y_pred)*100}")
  print(f"\n precision :{precision_score(y_test,y_pred)*100}")
  print(f"\n recall :{recall_score(y_test,y_pred)*100}")
  print(f"\n f1 Score :{f1_score(y_test,y_pred)*100}")

"""# **Undersampling**"""

normal = data[data['Class']==0]
fraud = data[data['Class']==1]

normal.shape

fraud.shape

normal_sample = normal.sample(n=473)

normal_sample.shape

new_data = pd.concat([normal_sample,fraud],ignore_index=True)

new_data.head()

new_data['Class'].value_counts()

x = new_data.drop('Class',axis = 1)
y = new_data['Class']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

classifier = {
    "Logistic Regression": LogisticRegression(),
    "Decision tree": DecisionTreeClassifier()
}

for name, clf in classifier.items():
  print(f"\n============{name}============")
  clf.fit(x_train,y_train)
  y_pred = clf.predict(x_test)
  print(f"\n Accuracy :{accuracy_score(y_test,y_pred)*100}")
  print(f"\n precision :{precision_score(y_test,y_pred)*100}")
  print(f"\n recall :{recall_score(y_test,y_pred)*100}")
  print(f"\n f1 Score :{f1_score(y_test,y_pred)*100}")

"""# **Over sampling**"""

x = new_data.drop('Class',axis = 1)
y = new_data['Class']

x.shape

y.shape

from imblearn.over_sampling import SMOTE
x_res, y_res = SMOTE().fit_resample(x,y)

x_train,x_test,y_train,y_test = train_test_split(x_res,y_res,test_size=0.2,random_state=42)

classifier = {
    "Logistic Regression": LogisticRegression(),
    "Decision tree": DecisionTreeClassifier()
}

for name, clf in classifier.items():
  print(f"\n============{name}============")
  clf.fit(x_train,y_train)
  y_pred = clf.predict(x_test)
  print(f"\n Accuracy :{accuracy_score(y_test,y_pred)*100}")
  print(f"\n precision :{precision_score(y_test,y_pred)*100}")
  print(f"\n recall :{recall_score(y_test,y_pred)*100}")
  print(f"\n f1 Score :{f1_score(y_test,y_pred)*100}")

dtc = DecisionTreeClassifier()
dtc.fit(x_res,y_res)

import joblib
joblib.dump(dtc,"Creditcard")
model = joblib.load("Creditcard")

pred = model.predict([
    [2.267534, -1.476301, -0.742684, -1.667604, -1.336074, -0.328817, -1.363695, -0.035563, -1.234341, 1.729344, 0.222519, -0.318989, 0.290836, -0.343916, -0.720614, -0.100158, 0.029761, 0.677244, 0.249209, -0.422331, -0.125079, 0.133961, 0.190664, -0.516989, -0.255951, -0.165642, 0.021167, -0.059689, -0.290060],
    [-0.564136, -0.045062, 0.819071, -1.252888, -0.116546, -1.259302, 0.422690, -0.185536, -1.715080, 0.603287, 1.253586, -0.800879, -1.238666, 0.433476, -0.415261, 0.798376, 0.277132, -0.833331, 1.053677, -0.054396, 0.351968, 0.924137, 0.140254, 0.534701, -0.124918, -0.221290, 0.028887, 0.084941, -0.293258],
    [-0.727644, 0.935565, 2.092828, 2.049417, 0.710078, 1.970719, 0.030369, 0.625961, -1.109345, 0.301198, 0.367489, 0.194835, 0.503386, 0.012512, 1.979922, -0.631139, 0.634273, -1.826101, -1.861146, -0.122195, 0.182385, 0.611065, 0.197802, -0.974645, -0.953991, -0.021603, 0.113242, 0.157917, -0.273468],
    [1.242710, -0.793228, 0.374053, -0.373310, -1.122169, -0.613830, -0.527705, -0.046421, -0.386690, 0.472604, -0.277636, -0.730544, -1.112867, -0.142040, -0.217191, 0.138256, 1.178149, -2.170078, 0.446955, 0.031929, 0.119069, 0.322489, -0.064382, 0.429902, 0.517229, -0.138345, 0.006656, 0.014720, -0.117582]
])

pred[0]

if pred[0] == 0:
  print("Normal Transaction")
else:
  print("Fraud Transaction")

!pip install streamlit pyngrok

import streamlit as st
import joblib
import numpy as np
import re

st.set_page_config(page_title="Fraud Detection", layout="centered")

model = joblib.load("Creditcard")

st.markdown("""
<style>
.main {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    margin-top: 120px;
}
.big-title {
    font-size: 40px;
    font-weight: 600;
    text-align: center;
}
.stTextArea textarea {
    border-radius: 25px;
    padding: 15px;
    font-size: 16px;
}
.stButton>button {
    border-radius: 25px;
    padding: 10px 30px;
    font-size: 16px;
}
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="main">', unsafe_allow_html=True)
st.markdown('<div class="big-title">💳 Credit Card Fraud Detection</div>', unsafe_allow_html=True)

input_data = st.text_area("", placeholder="Enter 29 transaction values separated by comma")

if st.button("Search"):
    values = re.split(r'[,\s]+', input_data.strip())
    values = list(map(float, values))
    values = np.array(values).reshape(1, -1)

    prediction = model.predict(values)

    if prediction[0] == 0:
        st.success("✅ Normal Transaction")
    else:
        st.error("🚨 Fraud Transaction")

st.markdown('</div>', unsafe_allow_html=True)

from pyngrok import ngrok


ngrok.set_auth_token("3AITKIev4kaFiD6KPevHCb3twKd_3nCgbqXXRd6dT2zaTzxaW")

public_url = ngrok.connect(8501)
print(public_url)

!streamlit run app.py &